-- Insert student users from CSV data into the users table
-- This will make them visible in Developer User Management

-- Clear existing student users if needed (optional)
-- DELETE FROM users WHERE role = 'student';

-- Insert student users
INSERT INTO users (full_name, email, role, student_id, department, created_date) VALUES
('Ace Edizon Abad', 'STU-001@smcc.edu', 'student', 'STU-001', 'CCIS', NOW()),
('Jia Acabo', 'STU-002@smcc.edu', 'student', 'STU-002', 'CCIS', NOW()),
('Kevin jun A. Maestro', 'STU-003@smcc.edu', 'student', 'STU-003', 'CCIS', NOW()),
('Jomari Betonio', 'STU-004@smcc.edu', 'student', 'STU-004', 'CCIS', NOW()),
('Diether Flores', 'STU-005@smcc.edu', 'student', 'STU-005', 'CCIS', NOW()),
('Trixia Lee Lope', 'STU-006@smcc.edu', 'student', 'STU-006', 'CCIS', NOW()),
('Eric', 'STU-007@smcc.edu', 'student', 'STU-007', 'CCIS', NOW()),
('Almer Bongcahig', 'STU-008@smcc.edu', 'student', 'STU-008', 'CCIS', NOW()),
('Sunshine Tejadillo', 'STU-009@smcc.edu', 'student', 'STU-009', 'CCIS', NOW()),
('Roselyn Saavedra', 'STU-010@smcc.edu', 'student', 'STU-010', 'CCIS', NOW()),
('Trisha Macarayan', 'STU-011@smcc.edu', 'student', 'STU-011', 'CCIS', NOW()),
('Emirald Sabandal', 'STU-012@smcc.edu', 'student', 'STU-012', 'CCIS', NOW()),
('Cheryl Atad', 'STU-013@smcc.edu', 'student', 'STU-013', 'CCIS', NOW()),
('Jay-uanie Mansartihan Binongcasan', 'STU-014@smcc.edu', 'student', 'STU-014', 'CCIS', NOW()),
('Ashly Llavan', 'STU-015@smcc.edu', 'student', 'STU-015', 'CCIS', NOW()),
('Benedict Licong', 'STU-016@smcc.edu', 'student', 'STU-016', 'CCIS', NOW()),
('Jane Ranario', 'STU-017@smcc.edu', 'student', 'STU-017', 'CCIS', NOW()),
('Mariel Ordiz', 'STU-018@smcc.edu', 'student', 'STU-018', 'CCIS', NOW()),
('Larianmar Pancho', 'STU-019@smcc.edu', 'student', 'STU-019', 'CCIS', NOW()),
('Reina Joyce Suazo', 'STU-020@smcc.edu', 'student', 'STU-020', 'CCIS', NOW()),
('Aijalon Sindo', 'STU-021@smcc.edu', 'student', 'STU-021', 'CCIS', NOW()),
('Althea Mae Custan', 'STU-022@smcc.edu', 'student', 'STU-022', 'CCIS', NOW()),
('Bea Taglucop', 'STU-023@smcc.edu', 'student', 'STU-023', 'CCIS', NOW()),
('Nilmay Pepito', 'STU-024@smcc.edu', 'student', 'STU-024', 'CCIS', NOW()),
('Ivy loque', 'STU-025@smcc.edu', 'student', 'STU-025', 'CCIS', NOW()),
('Hurry Kim R. Semana', 'STU-026@smcc.edu', 'student', 'STU-026', 'CCIS', NOW()),
('Eeyore Josh Chiong', 'STU-027@smcc.edu', 'student', 'STU-027', 'CCIS', NOW()),
('Honey Cabatingan', 'STU-028@smcc.edu', 'student', 'STU-028', 'CCIS', NOW()),
('Gerald Danuco', 'STU-029@smcc.edu', 'student', 'STU-029', 'CCIS', NOW()),
('Janryl Signar', 'STU-030@smcc.edu', 'student', 'STU-030', 'CCIS', NOW()),
('Bea Boniel', 'STU-031@smcc.edu', 'student', 'STU-031', 'CCIS', NOW()),
('REZZA MAE D. RELOSA', 'STU-032@smcc.edu', 'student', 'STU-032', 'CCIS', NOW()),
('Izzie Tadiarca', 'STU-033@smcc.edu', 'student', 'STU-033', 'CTHM', NOW()),
('Rosemarie Jen M. Buhisan', 'STU-034@smcc.edu', 'student', 'STU-034', 'CTHM', NOW()),
('Shahani Denise Almamento', 'STU-035@smcc.edu', 'student', 'STU-035', 'CTHM', NOW()),
('xyza', 'STU-036@smcc.edu', 'student', 'STU-036', 'CTHM', NOW()),
('Rhea Nicole B. Timbal', 'STU-037@smcc.edu', 'student', 'STU-037', 'CTHM', NOW()),
('Ahlex Mikaela Brodith', 'STU-038@smcc.edu', 'student', 'STU-038', 'CTHM', NOW()),
('Roxanne Gratol', 'STU-039@smcc.edu', 'student', 'STU-039', 'CTHM', NOW()),
('Mary', 'STU-040@smcc.edu', 'student', 'STU-040', 'CCIS', NOW()),
('Clark Justin S. Algarme', 'STU-041@smcc.edu', 'student', 'STU-041', 'CCIS', NOW()),
('JEN', 'STU-042@smcc.edu', 'student', 'STU-042', 'CTHM', NOW()),
('Jaila Conteniente', 'STU-043@smcc.edu', 'student', 'STU-043', 'CTHM', NOW()),
('Phoebe Kate Agregado Sincero', 'STU-044@smcc.edu', 'student', 'STU-044', 'CBM', NOW()),
('TM', 'STU-045@smcc.edu', 'student', 'STU-045', 'CTHM', NOW()),
('Linzy', 'STU-046@smcc.edu', 'student', 'STU-046', 'CTHM', NOW()),
('Honey Ahzel Delfin', 'STU-047@smcc.edu', 'student', 'STU-047', 'CTHM', NOW()),
('Ann Jenneth Gallenero', 'STU-048@smcc.edu', 'student', 'STU-048', 'CTHM', NOW()),
('Charlie sheen guergio', 'STU-049@smcc.edu', 'student', 'STU-049', 'CTHM', NOW()),
('Meryl Cajeles', 'STU-050@smcc.edu', 'student', 'STU-050', 'CTHM', NOW()),
('Angilyn L.Sulhayan', 'STU-051@smcc.edu', 'student', 'STU-051', 'CTHM', NOW()),
('Abigail Tanso', 'STU-052@smcc.edu', 'student', 'STU-052', 'CTHM', NOW()),
('RANDOM', 'STU-053@smcc.edu', 'student', 'STU-053', 'CTHM', NOW()),
('april jude D. Bernados', 'STU-054@smcc.edu', 'student', 'STU-054', 'CTHM', NOW()),
('Hannali Claire Redoble', 'STU-055@smcc.edu', 'student', 'STU-055', 'CTHM', NOW()),
('Brex Grande', 'STU-056@smcc.edu', 'student', 'STU-056', 'CTHM', NOW()),
('Cheryl Joy A. Matabaran', 'STU-057@smcc.edu', 'student', 'STU-057', 'CTHM', NOW()),
('Krystene L. Cabilogan', 'STU-058@smcc.edu', 'student', 'STU-058', 'CTHM', NOW()),
('Almer B. Bongcahig', 'STU-059@smcc.edu', 'student', 'STU-059', 'CCIS', NOW()),
('Rio Barcelon', 'STU-060@smcc.edu', 'student', 'STU-060', 'CCIS', NOW()),
('Maekyla A. Namoc', 'STU-061@smcc.edu', 'student', 'STU-061', 'CBM', NOW()),
('Jade Tanio Osorio', 'STU-062@smcc.edu', 'student', 'STU-062', 'CBM', NOW()),
('Blecy M. Soreño', 'STU-063@smcc.edu', 'student', 'STU-063', 'CBM', NOW()),
('John Phil Belmonte', 'STU-064@smcc.edu', 'student', 'STU-064', 'CCIS', NOW()),
('Jehmarie Alisoso', 'STU-065@smcc.edu', 'student', 'STU-065', 'CCIS', NOW()),
('Miko', 'STU-066@smcc.edu', 'student', 'STU-066', 'CCJE', NOW()),
('CHE', 'STU-067@smcc.edu', 'student', 'STU-067', 'CCIS', NOW()),
('Jae Montilla', 'STU-068@smcc.edu', 'student', 'STU-068', 'CCIS', NOW());
