"""
METHODOLOGY: Report Viewing and Metric Generation Test
This test measures the time required to generate graphical analytical reports. 
The script directly executes the `save_visualization_plots` function from 
app.py, bypassing the UI. It benchmarks the generation of the Confusion Matrix 
Heatmap and the Feature Importance Ranking Plot. The 'time' library records 
the duration of statistical calculation and filesystem I/O involved in saving 
high-resolution PNG files.
"""

import os
import time
import joblib
import numpy as np
from app import save_visualization_plots

def run_report_perf():
    results_dir = 'performance_test'
    if not os.path.exists(results_dir):
        os.makedirs(results_dir)

    # Load the actual model artifacts generated by the system
    if not os.path.exists('best_model.pkl'):
        print("Error: best_model.pkl not found. Run model_training_perf.py first.")
        return

    model = joblib.load('best_model.pkl')
    feature_names = [
        'study_hours', 'library_visits', 'lms_login_per_month', 'gpa_y1s1', 
        'gpa_y1s2', 'gpa_y2s1', 'gpa_y2s2', 'gpa_y3s1', 'scholarship_amount', 
        'family_income', 'like_course', 'interested_in_subjects', 'course_motivates',
        'satisfied_with_performance', 'previous_grades_affect', 'study_regularly', 
        'submit_on_time', 'manage_time_well', 'instructors_explain_clearly', 
        'approach_instructors', 'instructors_encourage', 'classmates_influence_positively', 
        'work_well_with_classmates', 'friends_motivate'
    ]
    
    # Simulate test data (30% split size)
    X_test = np.random.rand(30, 24)
    y_test = np.random.randint(0, 3, 30)

    print("Measuring Graphical Report Generation Time...")
    start_time = time.perf_counter()
    
    # Call the actual system visualization function
    report_dir = 'performance_test/test_reports'
    if not os.path.exists(report_dir): os.makedirs(report_dir)
    
    save_visualization_plots(model, X_test, y_test, feature_names, report_dir, "PERF_TEST")
    
    execution_ms = (time.perf_counter() - start_time) * 1000

    result_log = (
        f"\n--- Report & Plot Generation Test [{time.ctime()}] ---\n"
        f"Total Generation Time: {execution_ms:.2f} ms\n"
        f"Outputs: Confusion Matrix & Feature Importance Plots\n"
        f"----------------------------------------------------\n"
    )

    with open(os.path.join(results_dir, 'results.txt'), 'a') as f:
        f.write(result_log)
    print(result_log)

if __name__ == "__main__":
    run_report_perf()
